### ISSUE TITLE
[Solution to nft pricing in cross-chain] XClaim + harberger tax

### ISSUE THREAD

**Issue by sekisamu** [darwinia-network/rfcs#17]
> it's a solution to https://github.com/darwinia-network/rfcs/issues/16

### 问题描述
XClaim提供了一种对于fungible token友好安全的跨链解决方案，[paper链接](
https://eprint.iacr.org/2018/643.pdf).

在安全方面，部分关键点如下：
**Pricing**:  需要一个oracle来获取chain I 上的native token  *i* 对chain B上的native token  *b* 的价格关系；
**Over-collateralize**: 在抵押的总价值和真实价值之间需要有一定的容错空间,  *buffer* , 来保证价格波动时的安全。参考DAI.

以上两点均有一个前提，即 *i* 和 *b* 均需要有良好的流动性来保证定价。这对于fungible token相对更容易实现。
但是对于non-fungible token, 定价困难和流动性匮乏导致了XClaim在NFT跨链流转时，有较大的局限性。

### Oracle在NFT定价上的缺陷
因为定价是抵押的基础，所以解决了定价的问题，某种程度上，也就解决了足额/超额抵押的问题，从而保证了跨链的安全性。
在XClaim方案中，主要通过Oracle实现了喂价。但是Oracle在NFT定价中，有以下缺点：
1. NFT market市场规模小，流动性差；
2. NFT交易所太少，主观偏差大；
3. 每次跨链之前，均需要创建拍卖提供价格，用户操作成本高；

因此，在对待NFT的跨链上，需要有不一样的价格发现机制。

#### what is harberger tax
https://vitalik.ca/general/2018/04/20/radical_markets.html?source=post_page-----c2c99e866f87----------------------
https://talk.darwinia.network/topics/99

#### harberger tax in NFT bridging
假设目前全网已经存在了一些 *vaults* 并且抵押了一些 *i* ，当用户想chain B 上的NFT  *nft_b* 跨到chain I上时，需要：
- (i) 自己对 *nft_b* 声明一个价格 *price_b* ;
- (ii) 在chain I 确认当前是否有足够collateral i (| *i* | = | *price_b* |)；
- (iii) 如果(i)和(ii)成功通过的话，用户承诺一笔跨链金额，fee_ratio * *price_b* 用于支付跨链手续费；
- (iv) 如果 *nft_b* 在跨链中丢失或者发生了其他恶意操作的话，那么相应的 *vault* 会被扣除 *price_b* 等值的 *i* ，用于弥补用户的损失；如果跨链成功，这笔手续费就会被支付给相应的 *vault* .

here, harberger tax is more than taxation, it is an insurance and a way of price-finding.

#### 优点
1. 定价无需依赖oracle，在市场规模和流动性不足时，也可以定价成功；
2. 用户无需去外部的NFT交易所再单独实行定价操作；
3. 定价和成本之间存在线性关系，会给到 *vault* 足够的incentive

### 延伸
based on XClaim + harberger tax, 我们已经可以提供了基本的跨链价值保障。与此同时，我们也获得了一些价格发现机制，也可被视作某种pricing DAO，在此之上，也有机会发展成为NFT DEX protocol. （待续）

**Comment by hackfisher** [comment]
Here is a case need considering:

If the requester transferred NFT cross-chain to issuing chain using a low price_b, but sell to someone in high price?

Then, the buyer will price it in higher price(but vault didn't add collateral), would want to redeem on backing chain.

In this case, what if there is no sufficient collateral for vault on issuing chain to slash & compensate buyer if the redeem fails. 

Similar to the case in XClaim Sec. IV-D Mitigating Exchange Rage Functions (Redeemability)

**Comment by sekisamu** [comment]
@HackFisher we assume that only the owner of NFT has the rights to swap it from chain B to chain I. so if the owner wants to sell it at a higher price, he/she will lock it first in a specific auction contract, as he/she is no longer the owner of that NFT, the NFT is impossible to be locked in the `cross-chain lock` contracts any more. Hence the cross-chain operation would fail.

as what is said before, harberger tax here is more like an issuance, the NFT owner will need to declare a `harberger tax amount` every time when he/she wants it to cross-chain, so the vaults' collateral will also be verified each time the tax amount is declared. 
The amount the owner has declared may not 100% show the actual price, but a trade-off of the price, the security level of the whole cross-chain system, and something else.

**Comment by HackFisher** [comment]
This rfc and proposal has been abandoned:

**Comment by hackfisher** [comment]
This rfc and proposal has been abandoned:
https://github.com/darwinia-network/rfcs/blob/master/RFC/zh_CN/0011-using-harberger-tax-to-find-price-for-xclaim-vault-collaterals.md
