### ISSUE TITLE
关于Staking机制设计的思考(一）

### ISSUE THREAD

**Issue by sekisamu** [darwinia-network/rfcs#3]
### 问题描述

如果说PoW和PoS只是矿工/Validator关心的话题，那么Staking无疑把整个利益分配格局扩大到了生态的每一个参与者。整个生态里， validator、重度参与者、轻度使用者都共同作用塑造了整个生态。

对波卡来说，因为token没有cap，所以validator奖励是浮动的，可以更加灵活地塑造出共赢的staking模式，弱化了validator之间的竞争关系。

而对于darwinia来说，token存在cap是一把双刃剑。一方面cap的存在可以强化价值共识；而另一方面，因为有cap，在现有的模式下，就难以避免地导致某段时间内的增发是由公式决定，相对固定的，也是有cap的。

对于有cap的奖励，节点们之间相当于都在参加一个零和博弈，会导致节点之间的恶性竞争，不利于共建生态。

#### 1. 责任和权利对等

目前比较初级的一个解决办法，就是权责对等。validator的责任是出块，维护网络稳定。那么validator的奖励就和出块数成正比，建议这部分奖励剔除票数的影响。

#### 2 . 分配方式改进

目前每个分红era的奖励都有cap，为了保证darwinia token 100亿上限不被打破。但是继续细分到每一轮分红era，是否可以有更加灵活的分配方式(借鉴波卡)，让validator的竞争局面走出零和，这样才能更好地扩大生态。

**Comment by hackfisher** [comment]
> 对于有cap的奖励，节点们之间相当于都在参加一个零和博弈，会导致节点之间的恶性竞争，不利于共建生态。

零和博弈的观点不太赞同。

1. 节点们通过运维节点保护系统安全获得合理的系统回报，竞争是合理的，是否恶性要看全局的结果是往恶性走还是良性走。

2. 与是否有Cap也没有关系，Cap只是方便大家管理预期，以方便做出决策，并对货币政策做出一定约束，没有cap的通胀存在更多增发token的灵活性，但是每个人持有的token比例可能因为增发变少了，进而导致信任的问题。

利益相关方最终衡量token价值的不是看个数，看是看整个系统的价值，以及持有token比例(而非个数)。

货币政策是既定规则与自由裁量 (Rules vs Discretion) 的权衡，Cap是我们的既定规则(跟历史和既定共识有关系)，自由裁量通过Treasury和系统参数治理调节。

**Comment by hackfisher** [comment]
Reopen if there are new ideas input

**Comment by zzz6519003** [comment]
但觉厉
