### ISSUE TITLE
How to deploy flyclient on Chain Relay without forking BTC/Ethereum?

### ISSUE THREAD

**Issue by hackfisher** [darwinia-network/rfcs#35]
The FlyClient paper requires MMR to be included in the block header, thus the chain need to be hardfork/softfork/velvet fork any of these requires changes in the miner nodes of the network which is third party dependent and community driven.

So we need to find a solution for Chain Relays to fetch the correct MMR without forking BTC/Ethereum. 

Here I propose a way of recursive challenging the MMR value with the assumption that at least one of the witness relay workers has the correct value and economic rational.

Because the MMR is outside of blockheader and blockhash, so the POW works does not include it, thus MMR does not reach Nakamoto Consensus and an extra challenge mechanism need to be introduced to resolve this.

Anyone can summit blockheader with a MMR attached and collateral guarantee its correctness, if no one challenge it in the defined time, the MMR will be confirmed by the chain relay and the collateral can return back to the original worker. But, if there is another one challenge the MMR value, the conflicts MMRs will transit to an gaming status, untils someone else can give proof through prev_hash by recursively summit MMRs.

The maximum complexity of the progress is Log(N), and any economic rational attacker will not continue with the recursive attack progress because he is against all the honest workers and will lose all the collateral ultimately.

**Comment by Vincent4AI** [comment]
how about this work's process, I am curious about the usage of flyclient for chain relay.
