### ISSUE TITLE
RFC about how the KTON contract holder withdraw it staking RING

### ISSUE THREAD

**Issue by hackfisher** [darwinia-network/rfcs#6]
This could be a missing point in the design, better to demonstrate the current withdraw solution(supporting transfer in the mean time) which the idea was from P3D.

**Comment by hackfisher** [comment]
# 以太坊上一些常见的收益分配方案可以作为参考

## 回购销毁分红法

对通证进行销毁，其实是一种变相等价的分红方法，其他通证持有人手上的通证数量没有变化，但是比例上升，且供应量减少但对应系统的价值没有变化，本质上其实也是一种分红，具体案例参考BNB回购销毁分红。

该方法的缺点在于，需要分红通证和权益通证之间有较好的流通性市场，才能通过回购的方式将分红通证兑换成权益通证，进而将权益通证销毁进行分红，否则不适合使用此方法。

另外，虽然数学上回购销毁几乎等同于分红，但是从市场感知上不明显，从普通用户视角来看，不如看到账面上余额数字的增加来得容易感知。所以，实际效果上回购销毁不如直接分发。

## 冻结转账(P3D)分红方法

将主要以P3D为例解释这种通过合约进行分红的方法。

P3D严格意义上不同于ERC20通证，因为不支持通证转账功能，只存在购入和卖出两种方式变更通证持有者的余额。P3D因为这种简化反而对分红方法带来了简化，也就是只需要在通证持有者余额变化时更新持有者的分红数量，实现精确的合约分红。

具体实现是，维护以下账本，以权益通证P3D和分红币ETH为例：

Total_ETH_Dividends_Balance,  所有历史分红的总和，只会增加不会减少。每次分红的时候会增加。
My_ETH_Dividends_Balance_Claimed[address], 某P3D持有者放在系统保险箱里的ETH分红余额，刚开始为0，但是每次持有者P3D余额变化（购入，卖出）的时候ETH分红余额会更新并增加，持有者可以从中领取分红到自己的钱包，并相应减少。

Last_Claim_Total_ETH_Dividends_Balance[address], 某P3D持有者上一次Claim时，Total_ETH_Dividends_Balance的值，每次持有者余额变化（购入，卖出）的时候会更新。
每次持有者余额变化（购入，卖出）的时候，操作之前的P3D余额为balance_before, P3D总额为balance_total_before，操作之后的P3D余额为balance_after, P3D总额为balance_total_after，持有者的地址为address。则首先会进行第2、3账本的更新。
```
My_ETH_Dividends_Balance_Claimed[address] += {Total_ETH_Dividends_Balance - Last_Claim_Total_ETH_Dividends_Balance[address]} * [balance_before/balance_total_before]
Last_Claim_Total_ETH_Dividends_Balance[address] = Total_ETH_Dividends_Balance
```
进行其他P3D余额的变化

优点，去中心化方式，合约分账分红。缺点，可能需要锁定转账功能。

ERC20中持有者余额变化频繁，可以通过转账，发行，销毁等方式进行，如果每次转账都需要触发分红合约，会增加不必要燃料费，并增加合约复杂度，并且大多数ERC20通证并不支持在转账交易中做额外的事情。(部分ERC223可能支持，KTON的具体实现也比较复杂，友好支持程度偏悲观)。除非要求ERC20代币锁定之后，可以使用这个方法。

https://etherscan.io/address/0xb3775fb83f7d12a36e0475abdd1fca35c091efbe#code

**Comment by wuminzhe** [comment]
我的理解如下，是否正确:

每次p3d余额变动，就会计算profitPerShare：  
	`profitPerShare += (dividends / (tokenSupply))`  
我的分红余额：  
	`(profitPerShare * myTokenBalance) - myPayouts`

举一个简化的购买p3d例子，我分4次，每次100个eth购买p3d，其中10个拿来作分红，假设剩下的90个按1比1获得90个p3d:

|                                            |                                                          |0                 |0                   |0                 |
| -------------                              |-------------                                             | -------------    |  -------------     | -------------    | 
|myDividends_result                          |my_payouts                                                |profitPerShare    |dividends(eth)      |tokenSupply(p3d)  |
|0                                           |0                                                         |0                 |10                  |90                | 
|90 * 1/18 - my_payouts                      |90 * 1/18                                                 |1/18              |10                  |180               | 
|270 * (1/27+1/18) - my_payouts              |90 * (1/27+1/18) + 90 * 1/18                              |1/27+1/18         |10                  |270               | 
|360 * (1/36+1/27+1/18) - my_payouts         |90 * (1/36+1/27+1/18) + 90 * (1/27+1/18) + 90 * 1/18      |1/36+1/27+1/18    |10                  |360               | 

第一列计算后：

|                                                  |                                                           |0                 |0                   |0                 |     
| -------------                                    |-------------                                              | -------------    |  -------------     | -------------    | 
|myDividends_result                                |my_payouts                                                 |profitPerShare    |dividends(eth)      |tokenSupply(p3d)  | 
|0                                                 |0                                                          |0                 |10                  |90                | 
|90 * 1/18                                         |90 * 1/18                                                  |1/18              |10                  |180               | 
|180 * 1/27 + 90 * 1/18                            |90 * (1/27+1/18) + 90 * 1/18                               |1/27+1/18         |10                  |270               |     
|270 * 1/36 + 180 * 1/27 + 90 * 1/18               |90 * (1/36+1/27+1/18) + 90 * (1/27+1/18) + 90 * 1/18       |1/36+1/27+1/18    |10                  |360               |    

	老币能享受新的分红

简化代码如下：
[https://gist.github.com/wuminzhe/a244c91ec0870be61cc73664e5c2c094](https://gist.github.com/wuminzhe/a244c91ec0870be61cc73664e5c2c094)

**Comment by hackfisher** [comment]
@wuminzhe I agree with your understanding
